# Generated by Django 3.0.2 on 2020-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_article_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='username',
            new_name='user_name',
        ),
    ]
