# Generated by Django 3.0.2 on 2020-02-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200208_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user_name',
            field=models.TextField(),
        ),
    ]
