# Generated by Django 3.0.2 on 2020-02-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('incredient1', models.CharField(max_length=15)),
                ('incredient2', models.CharField(max_length=15)),
                ('incredient3', models.CharField(max_length=15)),
                ('incredient4', models.CharField(blank=True, max_length=15)),
                ('incredient5', models.CharField(blank=True, max_length=15)),
                ('incredient6', models.CharField(blank=True, max_length=15)),
                ('incredient7', models.CharField(blank=True, max_length=15)),
                ('incredient8', models.CharField(blank=True, max_length=15)),
                ('incredient9', models.CharField(blank=True, max_length=15)),
                ('incredient10', models.CharField(blank=True, max_length=15)),
                ('incredient11', models.CharField(blank=True, max_length=15)),
                ('incredient12', models.CharField(blank=True, max_length=15)),
                ('incredient13', models.CharField(blank=True, max_length=15)),
                ('incredient14', models.CharField(blank=True, max_length=15)),
                ('incredient15', models.CharField(blank=True, max_length=15)),
                ('incredient16', models.CharField(blank=True, max_length=15)),
                ('incredient17', models.CharField(blank=True, max_length=15)),
                ('step1', models.TextField(blank=True)),
                ('step2', models.TextField(blank=True)),
                ('step3', models.TextField(blank=True)),
                ('step4', models.TextField(blank=True)),
                ('step5', models.TextField(blank=True)),
                ('step6', models.TextField(blank=True)),
                ('step7', models.TextField(blank=True)),
                ('step8', models.TextField(blank=True)),
                ('step9', models.TextField(blank=True)),
                ('step10', models.TextField(blank=True)),
                ('step11', models.TextField(blank=True)),
                ('step12', models.TextField(blank=True)),
                ('step13', models.TextField(blank=True)),
                ('step14', models.TextField(blank=True)),
                ('step15', models.TextField(blank=True)),
                ('step16', models.TextField(blank=True)),
            ],
        ),
    ]
