# Generated by Django 3.0.2 on 2020-02-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='r_name',
            field=models.CharField(max_length=25),
        ),
    ]
