# Generated by Django 3.0.2 on 2020-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='step1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step3',
            field=models.TextField(),
        ),
    ]
