# Generated by Django 3.0.2 on 2020-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incredients',
            name='qty',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
