# Generated by Django 3.0.2 on 2020-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20200215_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='r_name',
            field=models.CharField(max_length=2),
        ),
    ]
