# Generated by Django 3.0.2 on 2020-02-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20200212_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='step1',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step10',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step11',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step12',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step13',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step14',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step15',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step16',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step8',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step9',
        ),
    ]
