# Generated by Django 3.0.2 on 2020-02-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_auto_20200214_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='incredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='step',
        ),
        migrations.AddField(
            model_name='recipe',
            name='r_id',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Incredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_1', models.CharField(max_length=20)),
                ('inc_2', models.CharField(max_length=20)),
                ('inc_3', models.CharField(max_length=20)),
                ('inc_4', models.CharField(max_length=20)),
                ('inc_5', models.CharField(max_length=20)),
                ('inc_6', models.CharField(blank=True, max_length=20)),
                ('inc_7', models.CharField(blank=True, max_length=20)),
                ('inc_8', models.CharField(blank=True, max_length=20)),
                ('inc_9', models.CharField(blank=True, max_length=20)),
                ('inc_10', models.CharField(blank=True, max_length=20)),
                ('inc_11', models.CharField(blank=True, max_length=20)),
                ('inc_12', models.CharField(blank=True, max_length=20)),
                ('r_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipies.Recipe')),
            ],
        ),
    ]
