# Generated by Django 3.0.2 on 2020-02-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_auto_20200216_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='seen',
        ),
    ]
