# Generated by Django 3.0.2 on 2020-02-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='r_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
