# Generated by Django 3.0.2 on 2020-02-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_remove_recipe_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incredients',
            name='qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='r_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
