# Generated by Django 3.0.2 on 2020-02-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0009_auto_20200216_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
