# Generated by Django 3.0.2 on 2020-02-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0009_auto_20200215_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incredients',
            old_name='r_id',
            new_name='r_name',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='r_id',
            new_name='r_name',
        ),
        migrations.RemoveField(
            model_name='incredients',
            name='inc_11',
        ),
        migrations.RemoveField(
            model_name='incredients',
            name='inc_12',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='r_id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='r_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
