# Generated by Django 3.0.2 on 2020-02-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0010_auto_20200215_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='r_id',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
